### ISSUE TITLE
prevent cloning to much

### ISSUE THREAD

**Issue by nbari** [s3mon/s3mon#4]
Need code review / refactor to prevent cloning to much, probably using lifetimes would be better

https://github.com/s3mon/s3mon/blob/master/src/main.rs#L46-L53

**Comment by Thiez** [comment]
I was just taking a peek and this issue confuses me. So perhaps you could save a handful of allocations per bucket, but surely that is utterly dwarfed by the cost of creating threads and performing network IO?

**Comment by nbari** [comment]
Hi @Thiez I was using before https://github.com/s3mon/s3mon/blob/844bb8e854f08282a6fbb2dbf811176f4e4fb0f0/src/main.rs#L43-L53, now to speed up things I am creating a thread per object

**Comment by Thiez** [comment]
I see. I still think that there isn't much runtime speed to be gained by going into this direction. However, it seems that rusoto is async-ready, so instead of spawning a thread per bucket (and immediately calling `.sync()`) your application could be made to "properly" use asynchronous programming. Depending on the typical number of buckets that you check that also might not get you much performance (if any), but when you have hundreds it could make a difference.

I'd be intrigued by this if it wasn't for the fact that I've never used an S3 bucket in my life, so I can be of no assistance :)

**Comment by nbari** [comment]
The next step will be to make it full asynchronous, for now, I still dealing with the basics however any feedback, suggestions are more than welcome.

**Comment by nbari** [comment]
https://github.com/s3mon/s3mon/issues/7
